const data = [

    {
        _study: "NHS GMSS case study",
        _intro: `
        The global pandemic caused by COVID-19 has taught us many things about the way we live and work. For NHS Greater Manchester Shared Services, it put into practice months of hard work and demonstrated the value of ISO....
        `,
        _detail: `The global pandemic caused by COVID-19 has taught us many things about the way we live and work. For NHS Greater Manchester Shared Services, it put into practice months of hard work and demonstrated the value of ISO 27001 certification.<br><br>
        Eighteen months ago, Phil Scott, IT Security Manager at NHS Greater Manchester Shared Services (GMSS), and his team made the decision to work towards ISO 27001 certification with leading certification provider, BM TRADA. The certification was awarded in mid-June, by which time the benefits of the process were already clear to see.<br><br>
        Working as a partner in the health and care system, GMSS customers include Clinical Commissioning Groups, GPs and NHS Foundation Trusts. With a number of major data breaches in the healthcare industry hitting the headlines, it was clear that data protection was an area of significant concern for their clients. While many organizations in the industry looked to a cyber training provider for guidance, Phil decided to take the IT security of the organization even further. <br><br>
        “I was brought in to improve IT security, and I wanted to make sure we were leading the way in this area,” he explains. “Certification would prove to our customers how seriously we deal with security and give confidence in our services. We wanted to offer the highest level of security, so we looked to ISO 27001, making us one of the first NHS organizations to do so.” <br><br>
        ISO 27001 is an information security management system (ISMS), which outlines a framework of policies and procedures to mitigate the risk of a security breach. Covering more than just IT and cyber security, the certification provides a model for establishing, implementing, operating, monitoring, reviewing, maintaining and improving an ISMS, and covers all aspects of an organization’s information risk management process. <br><br>
        “With ISO 27001, everything is considered, including policies and ways of working,” explains Phil. “The auditor from BM TRADA who undertook the first audit wasn’t there just to check what we were doing; he was professional, knowledgeable and extremely thorough, and crucially, he offered advice and guidance for the second audit, which was so useful.” <br><br>
        When the initial audit took place in February 2020, the team could not have anticipated the challenges that would lie ahead for them. Mohamed Fadil, Risk, Audit and Business Continuity Manager at GMSS explains, “We knew ISO 27001 certification would make us leaders in our field, but we didn’t realize what a difference it would make to our organization in the coming months as we faced a global pandemic. <br><br>
        “With a business continuity management system and risk assessment framework in place, we started planning for COVID-19 much earlier than most. At the end of February, there were whisperings of an epidemic heading our way, so we undertook a tabletop exercise to see what would happen if there was an outbreak in the UK and if there were confirmed infections in our offices. This outlined the weaknesses that we needed to address, resulting in 13 learnings to consider. For example, we identified that we would need to increase our remote access capacity, which brings its own risks. We anticipated some of these potential problems and dealt with them in advance. By the time the Prime Minister announced on 23 March that everyone should stay home, we had a process in place to act immediately. All 350 employees could work from home safely the following day.” <br><br>
        As well as its employees, GMMS needed to consider the 13,000 service-users through its clients. While others around the country were placing emergency orders for laptops and equipment and discovering that stock was low, GMSS was able to deploy 2,300 laptops and many more hardware kits between March and June, and increased capacity from 2,000 concurrent users to 10,000 – which was enough to cover the required number of people to use its services at any one time. Businesses who needed support most urgently at this incredibly challenging time were able to continue to work seamlessly. <br><br>
        “Anyone who was working with us was able to work from home quickly and easily, while other healthcare providers were still struggling months later. The feedback we received was incredible. Over a normal period, we receive a mixture of positive and negative feedback, but during the COVID-19 period, the feedback was overwhelmingly positive, and our customers could clearly see the changes in our organisation. This was a significant difference from 18 months ago, and it really boosted team morale.” <br><br>
        As the experience at GMSS demonstrates, a key benefit of ISO 27001 certification is business retention and development, as it provides assurance to customers, employees, stakeholders and the wider industry. It also helps organizations demonstrate their willingness to comply with legal obligations, as well as potentially preventing fines, legal repercussions and reputational damage resulting from security breaches. <br><br>
        “For me, the most important thing about ISO 27001 is the culture change that it instils,’ explains Phil. “Other certification can just be a rubber stamp exercise that everyone ticks off and then forgets about, but with ISO 27001, it’s different. We all have to keep thinking about it and we all understand why we’re doing it.” <br><br>
        Mohamed adds, “Processes and policies are great, but you need people to buy into them to really succeed. ISO becomes part of the ‘business as usual’ and changes the way that everyone works as a result. It has certainly changed the culture when assessing risk. Our team understands the value of what we’re doing, and once the framework was in place, everyone could see how useful it was; making things much easier and safer all round.” <br><br>
        Despite the onset of COVID-19 and the subsequent lockdown of the country, the final part of the audit was able to take place. Phil explains, “the process was really straight-forward, but we did have a challenge to complete it, as the final audit had to be done remotely. However, the team at 
        BM TRADA was fantastic, and we were able to demonstrate enough through video calls for it to work. The audits were very well organized and scheduled to perfection, so thankfully, we managed to make it work.” <br><br>
        Adam Colyer, Business Development Manager at BM TRADA adds: “Becoming certified to ISO 27001 demonstrates that an organization has been assessed at a globally-recognized standard and has assessed its risks and incorporated procedures to protect its information. While there is an initial investment of time and money, it is far less than the time, cost and reputational implications that will be incurred as a result of a preventable breach. <br><br>
        “Our team has many decades of experience and provides a certification process that is thorough and robust, striving to provide clarity and support along the way. And using a UKAS-accredited certification body like us ensures the ISO 27001 certification will be readily accepted by many regulators, suppliers and purchasers across the world. <br><br>
        “With a significant rise in people working from home, cyber security is open to more breaches than ever before. As we all re-consider the safety of our workplaces, businesses should also pay extra attention to the safety of the data that they hold.” <br><br>
        BM TRADA, part of the Element Group, specializes in providing a comprehensive range of independent testing, inspection, certification, technical and training services. We help organizations to demonstrate their business and product credentials and to improve performance and compliance. 
        We exist to help our customers to make certain that the management systems, supply chain and product certification schemes they operate are compliant and fit for purpose. <br><br>
        `
    },
    {
        _study: "KATLAS Technology Ltd ",
        _intro: `Katlas Technology has developed MAI Health, a clinical system comprising platforms and a portal that enables fast-track, remote monitoring of healthcare.<br><br> MAI Health integrates with medical devices and an AI engine (NEOS) to provide a Proximity Care Model (MAP), a systematic methodology for the early detection and prevention of cardiovascular disease and broader...`,
        _detail: `
        Katlas Technology has developed MAI Health, a clinical system comprising platforms and a portal that enables fast-track, remote monitoring of healthcare. <br><br>
        MAI Health integrates with medical devices and an AI engine (NEOS) to provide a Proximity Care Model (MAP), a systematic methodology for the early detection and prevention of cardiovascular disease and broader long-term conditions. <br><br>
        In pilot testing, MAI Health has demonstrated speedy data gathering, management and presentation of information back to the individual in the form of their own personalised health wallet. <br><br>
        This approach places the patient at the centre of their own healthcare. They can use findings from clinical screenings, socio-economic and lifestyle factors to consult with their GP remotely, who would then review findings, conduct an online diagnosis and prescription. <br><br>
        The implications for the NHS and other healthcare providers of this innovative patientcentered healthcare are considerable, including optimization of current health resources (human and technological), improvements in the efficiency and effectiveness of patient and public health information management systems, rapid triage services and cost savings. <br><br>
        AI Health has the potential to revolutionise the way in which healthcare is delivered whilst preventing premature deaths from cardiovascular disease, the prime cause of heart disease, Alzheimer’s and dementia, namely the biggest killers of men and women in the UK. <br><br>
        The Challenge  <br><br>
        A huge amount of information is being captured by the NHS each day. Vital patient information sits as data spread across disparate systems across different organisations within the NHS. In the absence of a common platform to search for and then analyse this data, effective patient information management has proved expensive and technically difficult to achieve. The NHS is a reactive service, it is only by being able to integrate these data systems will it be capable of finding the solution to addressing preventable deaths. Combatting cardiovascular disease at an early stage is a big issue for the NHS. The potential for achieving this is within its grasp, as the algorithms for analysing patient data are there. However, centralised systems are not safe, slow to interrogate and require significant human resources to manage them. Combined with insufficient level of securities that one might expect of sensitive information, the result is an ineffective health information service which; <br><br>
        • increases waiting times for appointments<br>
         • requires unnecessary travel arrangements <br>
        • affects patient communication with GPs<br>
         • can cause disputes between health professionals prescribing and dispensing treatments<br>
         • is open to security breaches <br>
         • causes significant anxiety for patients when making appointments<br><br>
        To date, personalised care with AI integration cannot be delivered because patient data captured remotely from medical devices was unreliable and unsecure. <br><br>
        Solution<br><br>
        MAI Health is a medical data service that puts the patient in charge of their own health and wellbeing. MAI Health uses blockchain technology to integrate with all major clinical systems. <br><br>
        Each individual has all their personal healthcare information safely contained in a digital ‘wallet’, which they control access to. By controlling who sees their data and when, individuals have a greater level of control of their own appointments, treatments and patient history. MAI Health can deliver the reports that the GP needs to know to determine a range of options or treatments. <br><br>
        My (AI) Health puts patients in control of their personal health 24/7. Importantly, our product puts GDPR consent at the heart of every transaction. Our data management platform maximises privacy, minimises disputes and ensures all resources are tracked and accounted at the point of use. <br><br>
        Our pilot work to date has sought to show how interaction between GP practices and patients can improve by enabling people to take control of their health issues, safely and securely. <br><br>
        Services<br><br>
        MAI Health is different from other health apps in the marketplace because it is powered by high performance KATLAS Blockchain technology that is demonstrably superior than anything else available in the marketplace. <br><br>
        The COVID19 pandemic has exposed the need for a more efficient clinical system that can monitor patient data remotely. This has presented an opportunity to test the effectiveness of using Katlas Technology’s innovative blockchain network to secure and communicate patient data. The scope of patient data monitored has covered COVID-19 symptoms but as importantly broader long-term condition management in cardiovascular disease (CVD). <br><br>
        MAI Health can support functionality that just does not exist elsewhere. This concept is proven by integrating patient data to AI and medical devices to show an unbroken chain of data from IoMT to GP. <br><br>
        Benefits<br><br>
        For patients, the main benefits are; <br><br>
        • Improved communication with doctors and other healthcare professionals. <br><br>
        • Reduces waiting times, wasted trips to the pharmacy and missed appointments.  <br><br>
        • Responses to medical questions without leaving home. <br><br>
        • Quicker access to test results. <br><br>
        • Patients own and control who they share their data with <br><br>
        • Patient consent in every transaction For the NHS, GPs, clinicians, hospital trusts and CCGs, the main benefits are; <br><br>
        • Cost savings, with automated services enabling faster delivery of proximity care. <br><br>
        • Data surety, solving privacy and consent (KYC and GDPR) <br><br>
        • Saving time and resources spent chasing up referrals, managing disputes and checking identification reduced by 90%. <br><br>
        • More efficacious patient booking and resource management, reducing workload<br><br>
        • Safer, compliant integration with medical devices (IoMT)   <br><br>
        • Minimal disruption, with GPs, hospitals, CCGs, Foundation Trusts, patients, machines, pharmacies, and third-party vendors simply accessing cloud services to join network. <br><br>
        • Improved interaction between GP practices and patients by encouraging people to take control of their health<br><br>
        Case Study – Microcirculatory and cardiovascular health prevention<br><br>
        A sample group of 60 patients was selected based on their propensity to suffer from future cardiovascular problems; <br><br>
        • 30 males comprising those aged 40-55 (a typically under-reported group which may have hidden symptoms) and those aged 55-70 (higher priority group) with high risk of hypertension. <br><br>
        • 30 females comprising those aged 50-70 (with possible hidden symptoms) and those aged 40-50 with high stroke risk. <br><br>
        Each individual was screened, supported by the use of biomedical devices, for clinical, psycho-social and socio-economic measures to determine the health status and likely future prognosis of the individual. Data was analysed using an Artificial Intelligence and Machine Learning system NEOS to provide a comprehensive health profile of each individual. <br><br>
        Results were achieved in a quicker time than previously possible with a predicted prognosis for each individual with advice on treatment and lifestyle changes. This proactive process of, screening, testing and preventory diagnosis was particularly valuable for one individual who was found to have the early stages of a pulmonary infarction and subsequently successfully treated. <br><br>
        Early Conclusions from Pilot Work<br><br>
        The MAI Health system is capable of delivering triage services within a much quicker timescale than currently capable, which in itself saves lives. It can provide proactive care, grade a patient’s condition (high/med/low risk) and recommend treatments or programmes, all supported by apps. <br><br>
        MAI Health can detect conditions and cases that would have been missed with traditional techniques<br><br>
        There are significant benefits in cost savings for the NHS and other healthcare providers, taking out the lower value element of the service and offering a different model for healthcare. With this will emerge a new job, that of health coach, who will be able to deploy mobile services and utilise the technology to assist both patients and healthcare professionals. GPs will pay a fee for this service. <br><br>
        Katlas Technology will provide the technology pipeline with blockchain software on which other applications, such as wearable medical device software will sit to collect data. The blockchain will integrate previously autonomous systems with the IOMT through nodes and link to other systems to co-ordinate service delivery to individuals in their home. <br><br>
        We are currently at the proof of concept stage and are delivering better results, now seeking need more clinical data for further trials. 
        `
    }

]

export default data